server:
  port: 8080

logging:
  file: /usr/local/logs/app.log
  level:
    root: INFO

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/topm
    username: postgres
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: postgres

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

